src/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CircleCreateView, CircleDeleteView

app_name = 'account'
urlpatterns = [
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/profile/<str:username>/',
         views.profile_view, name='profile'),
    path('accounts/profile/<str:username>/edit/',
         views.edit_profile_view, name='edit_profile'),
    path('accounts/profile/<str:username>/remove_pic/',
         views.remove_profile_pic, name='remove_profile_pic'),
    path('accounts/profile/<str:username>/remove_banner/',
         views.remove_banner_pic, name='remove_banner'),
    path('accounts/profile/inbox/<str:username>/', views.inbox, name='inbox'),
    path('inbox/conversation/<str:username>/<int:message_id>/',
         views.conversation, name='conversation'),

    path('accounts/profile/circle/<str:circle_name>/',
         views.circle_detail_view, name='circle-detail'),
    path('accounts/profile/circle/<int:pk>/delete/',
         CircleDeleteView.as_view(), name='circle-delete'),
    path('accounts/profile/cir/create/',
         CircleCreateView.as_view(), name='circle-create'),

    path('accounts/profile/<str:username>/notifications/',
         views.notification, name='notifications'),

    path('accounts/profile/circle/<str:circle_name>/like',
         views.like_view, name='like'),



]

src/app/urls.py
from django.urls import path
from . import views

from .views import BookmarkListView,  CategoryListView, SearchView, PostDeleteView, HashtagsView

urlpatterns = [
    path('', views.home, name='home'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    
    path('post/<int:post_id>/repost/', views.repost_view, name='repost'),


    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete_view, name='comment-delete'),

    path('post/<int:post_pk>/comment/<int:comment_pk>/<int:reply_pk>/delete/', views.reply_delete_view, name='reply-delete'),


    path('search/', views.SearchView.as_view(), name='search'),
    path('hashtags/', HashtagsView.as_view(), name='hashtags'),
    
    path('people_search', views.people_search, name='people_search'),

    

    path('post/<slug:slug>/upvote/', views.upvote, name='upvote'),
    path('post/<slug:slug>/downvote/', views.downvote, name='downvote'),  

    path('accounts/profile/bookmark_list/', BookmarkListView.as_view(),  name='bookmark_list'), 

    path('post/<slug:slug>/add_to_bookmark', views.add_or_remove_bookmark, name='add_to_bookmark'),
    path('post/<slug:slug>/remove_from_bookmark', views.add_or_remove_bookmark, name='remove_from_bookmark'),




    path('create_post/', views.create_post_view, name='create_post'), 

    path('add-choice/<slug:slug>/', views.add_choices, name='add_choices'), 
    path('delete-choice/<int:pk>/', views.delete_choice, name='delete_choice'),

    path('category/<str:category>/', CategoryListView.as_view(), name='tag'), 

    path('group_search/', views.group_search, name='group_search'), 

    


    
]

src/web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),

    path('', include('account.urls')),

    path('', include('django.contrib.auth.urls')),



    path("__reload__/", include("django_browser_reload.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/account/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to='images/pfp', blank=True)
    banner = models.ImageField(upload_to='images/banners/', blank=True)
    bio = models.TextField(blank=True)
    website = models.URLField(max_length=150, blank=True)
    following = models.ManyToManyField(
        'self', symmetrical=False, related_name='followers', blank=True)
    created_at = models.DateTimeField(default=datetime.now)
    is_active = models.BooleanField(default=False)
    is_verify = models.BooleanField(default=False)

    CONTINENT_CHOICES = (
        ('Africa', 'Africa'),
        ('Antarctica', 'Antarctica'),
        ('Asia', 'Asia'),
        ('Europe', 'Europe'),
        ('North America', 'North America'),
        ('Oceania', 'Oceania'),
        ('South America', 'South America'), )

    location = models.CharField(
        max_length=20, choices=CONTINENT_CHOICES, blank=True)

    def __str__(self):
        return self.user.username

    def __str__(self):
        return f'{self.user.username} -followers: {self.followers.count()}'

from .signals import *

class Inbox(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-created_at']


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.profile.user.username


class Circle(models.Model):
    PRIVACY_CHOICES = [
        ('private', 'Private'),
        ('public', 'Public'),]

    host = models.OneToOneField(User, on_delete=models.CASCADE)
    pfp = models.ImageField(upload_to='Circle_pfps/', blank=True, null=True)
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField(blank=True)
    members = models.ManyToManyField(User, related_name='people', blank=True)
    privacy = models.CharField(
        max_length=10, choices=PRIVACY_CHOICES, default='public')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class CirclePost(models.Model):
    circle = models.ForeignKey(Circle, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=280, blank=True)
    img = models.ImageField(upload_to='circle_post_images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Post in {self.circle}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    circlepost = models.ForeignKey(CirclePost, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}: {self.circlepost.title[:20]}'

src/app/templates/includes/htmx/group_search_results.html
{% load static %}
{% load custom_tags %}

<ul class="space-y-4">
  {% if results %}
    {% for result in results %}
      <li class="bg-transparent hover:bg-opacity-80 rounded-md p-2 relative transition duration-300">
        <div class="flex gap-2">
          <div>
            {% if result.pfp %}
              <img src="{{ MEDIA_URL }}{{ result.pfp.url }}" alt="Profile Picture" class="smoothing border border-stone-200 rounded-md object-cover w-12 h-12" />
            {% else %}
              <div class="bg-purple-500 shadow-inner rounded-md flex justify-center items-center text-2xl text-white w-12 h-12">?</div>
            {% endif %}
          </div>

          <div class="flex flex-col">
            <div class="flex items-center gap-2">
              <h3 class="text-lg text-white font-semibold overflow-hidden break-words max-w-[120px]"><a class="hover:text-white hover:underline" href="{% url 'account:circle-detail' result.name %}">{{ result.name }}</a></h3>
              {% if result.privacy == 'private' and request.user not in result.members.all %}
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 text-gray-400">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 10.5V6.75a4.5 4.5 0 10-9 0v3.75m-.75 11.25h10.5a2.25 2.25 0 002.25-2.25v-6.75a2.25 2.25 0 00-2.25-2.25H6.75a2.25 2.25 0 00-2.25 2.25v6.75a2.25 2.25 0 002.25 2.25z" />
                </svg>
              {% endif %}
              <small class="text-gray-400">{{ result.circlepost_set.all.count }} posts</small>
            </div>

            <p class="text-gray-400 text-xs">{{ result.members.count }} members</p>
          </div>

          {% if result.host == request.user %}

          {% else %}
            {% if user.is_authenticated %}
              <form method="post" class="join-leave-form absolute right-0 top-1" action="{% url 'account:circle-detail' result.name %}">
                <input type="hidden" name="join_leave" value="true" />

                {% csrf_token %}
                <div class="flex items-center">
                  {% if request.user in result.members.all %}
                    <button type="submit" id="join-leave-button" class="border hover:opacity-60 text-white font-semibold py-1 px-2 rounded-lg text-xs" name="action" value="leave">Leave</button>
                  {% else %}
                    <button type="submit" id="join-leave-button" class="border hover:opacity-60 text-white font-semibold py-1 px-2 rounded-lg text-xs" name="action" value="join">Join</button>
                  {% endif %}
                </div>
              </form>
            {% endif %}
          {% endif %}
        </div>
        <div class="overflow-hidden max-h-auto">
          <!-- Add a maximum height -->
          <p class="text-gray-300 text-sm mt-2">{{ result.description|truncatechars:250 }}</p>
        </div>
      </li>
    {% endfor %}
  {% else %}
    <li class="text-gray-600 text-lg text-center mt-4">No results found.</li>
  {% endif %}
</ul>

src/app/templates/includes/htmx/people_search_results.html
{% load static %}
{% load custom_tags %}
{% if results %}
  <div id="post-template">
    {% for result in results %}
      <div class="bg-transparent hover:bg-opacity-80 p-2 relative transition duration-300">
        <div class="flex gap-3">
          <div class="flex items-center gap-2">
            {% if result.profile.user.pic  %}
            <a href="{% url 'account:profile' result.profile.user %}">
           
                <img src="{{ MEDIA_URL }}{{ result.profile.pic.url }}"
                     alt="Profile Picture"
                     class="smoothing rounded-full object-cover "
                     style="width:37px;
                            height:37px" />
              </a>
            {% else %}
            <a href="{% url 'account:profile' result %}">
                <img src="{% static 'account/images/default_pic.jpg' %}"
                     alt="Default Profile Picture"
                     class="rounded-full"
                     style="width:37px;
                            height:37px" />
              </a>
            {% endif %}
            <div class="flex flex-col">
              {{ result.profile.user }}
              <small class="text-emerald-600">{{ result.last_login|elapsed_time }}</small>
            </div>
          </div>
          {% if request.user != result.profile.user %}
            <form class="follow-form"
                  method="POST"
                  action="{% url 'account:profile' result %}">
              {% csrf_token %}
              <input type="hidden" name="follow_unfollow" value="true">
              {% if result.profile in request.user.profile.following.all %}
                <button class="bg-gray-800 hover:bg-opacity-75 px-2 py-1 rounded-md font-semibold"
                        type="submit"
                        name="toggle"
                        value="unfollow">Unfollow</button>
              {% else %}
                <button class="bg-[#2911B3] hover:bg-opacity-75 px-3 py-1 rounded-md font-semibold"
                        type="submit"
                        name="toggle"
                        value="follow">Follow</button>
              {% endif %}
            </form>
          {% endif %}
        </div>
        <span class="text-sm text-waikawa-gray-400">{{ result.profile.bio|truncatechars:135 }}</span>
      </div>
    {% endfor %}
  </div>
{% else %}
  <li class="text-gray-600 text-lg text-center mt-4">No results found.</li>
{% endif %}