src/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CircleCreateView, CircleDeleteView

app_name = 'account'
urlpatterns = [
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/profile/<str:username>/',
         views.profile_view, name='profile'),
    path('accounts/profile/<str:username>/edit/',
         views.edit_profile_view, name='edit_profile'),
    path('accounts/profile/<str:username>/remove_pic/',
         views.remove_profile_pic, name='remove_profile_pic'),
    path('accounts/profile/<str:username>/remove_banner/',
         views.remove_banner_pic, name='remove_banner'),
    path('accounts/profile/inbox/<str:username>/', views.inbox, name='inbox'),
    path('inbox/conversation/<str:username>/<int:message_id>/',
         views.conversation, name='conversation'),

    path('accounts/profile/circle/<str:circle_name>/',
         views.circle_detail_view, name='circle-detail'),
    path('accounts/profile/circle/<int:pk>/delete/',
         CircleDeleteView.as_view(), name='circle-delete'),
    path('accounts/profile/cir/create/',
         CircleCreateView.as_view(), name='circle-create'),

    path('accounts/profile/<str:username>/notifications/',
         views.notification, name='notifications'),

    path('accounts/profile/circle/<str:circle_name>/like',
         views.like_view, name='like'),



]

src/app/urls.py
from django.urls import path
from . import views

from .views import BookmarkListView,  CategoryListView, SearchView, PostDeleteView, HashtagsView

urlpatterns = [
    path('', views.home, name='home'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    
    path('post/<int:post_id>/repost/', views.repost_view, name='repost'),


    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete_view, name='comment-delete'),

    path('post/<int:post_pk>/comment/<int:comment_pk>/<int:reply_pk>/delete/', views.reply_delete_view, name='reply-delete'),


    path('search/', views.SearchView.as_view(), name='search'),
    path('hashtags/', HashtagsView.as_view(), name='hashtags'),
    
    path('people_search', views.people_search, name='people_search'),

    

    path('post/<slug:slug>/upvote/', views.upvote, name='upvote'),
    path('post/<slug:slug>/downvote/', views.downvote, name='downvote'),  

    path('accounts/profile/bookmark_list/', BookmarkListView.as_view(),  name='bookmark_list'), 

    path('post/<slug:slug>/add_to_bookmark', views.add_or_remove_bookmark, name='add_to_bookmark'),
    path('post/<slug:slug>/remove_from_bookmark', views.add_or_remove_bookmark, name='remove_from_bookmark'),




    path('create_post/', views.create_post_view, name='create_post'), 

    path('add-choice/<slug:slug>/', views.add_choices, name='add_choices'), 
    path('delete-choice/<int:pk>/', views.delete_choice, name='delete_choice'),

    path('category/<str:category>/', CategoryListView.as_view(), name='tag'), 

    path('group_search/', views.group_search, name='group_search'), 

    


    
]

src/web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),

    path('', include('account.urls')),

    path('', include('django.contrib.auth.urls')),



    path("__reload__/", include("django_browser_reload.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/account/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to='images/pfp', blank=True)
    banner = models.ImageField(upload_to='images/banners/', blank=True)
    bio = models.TextField(blank=True)
    website = models.URLField(max_length=150, blank=True)
    following = models.ManyToManyField(
        'self', symmetrical=False, related_name='followers', blank=True)
    created_at = models.DateTimeField(default=datetime.now)
    is_active = models.BooleanField(default=False)
    is_verify = models.BooleanField(default=False)

    CONTINENT_CHOICES = (
        ('Africa', 'Africa'),
        ('Antarctica', 'Antarctica'),
        ('Asia', 'Asia'),
        ('Europe', 'Europe'),
        ('North America', 'North America'),
        ('Oceania', 'Oceania'),
        ('South America', 'South America'), )

    location = models.CharField(
        max_length=20, choices=CONTINENT_CHOICES, blank=True)

    def __str__(self):
        return self.user.username

    def __str__(self):
        return f'{self.user.username} -followers: {self.followers.count()}'

from .signals import *

class Inbox(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-created_at']


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.profile.user.username


class Circle(models.Model):
    PRIVACY_CHOICES = [
        ('private', 'Private'),
        ('public', 'Public'),]

    host = models.OneToOneField(User, on_delete=models.CASCADE)
    pfp = models.ImageField(upload_to='Circle_pfps/', blank=True, null=True)
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField(blank=True)
    members = models.ManyToManyField(User, related_name='people', blank=True)
    privacy = models.CharField(
        max_length=10, choices=PRIVACY_CHOICES, default='public')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class CirclePost(models.Model):
    circle = models.ForeignKey(Circle, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=280, blank=True)
    img = models.ImageField(upload_to='circle_post_images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Post in {self.circle}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    circlepost = models.ForeignKey(CirclePost, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}: {self.circlepost.title[:20]}'

src/app/models.py
from django.db import models
from django.contrib.auth.models import User

#automatically add a slug 
from django.utils.text import slugify

from account.models import Profile




# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    file = models.FileField(upload_to='files/', null=True, blank=True) 
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    choices_added = models.BooleanField(default=False)

    #automatically add a unique slug 
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            unique_slug = base_slug
            suffix = 1
            
            while Post.objects.filter(slug=unique_slug).exists():
                suffix += 1
                unique_slug = f"{base_slug}-{suffix}"

            self.slug = unique_slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

#TAG
class Tag(models.Model):
    text = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE) 

    def __str__(self):
        return f'{self.text}: {self.post.title}'

class Upvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    upvotes = models.ManyToManyField(User, related_name='post_upvotes') #CHANGE 
    
    class Meta:
        unique_together = ('user', 'post') 

    def __str__(self):
        return f'{self.user.username}: {self.post.id}'

   
        
            


class Downvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    downvotes = models.ManyToManyField(User, related_name='post_downvotes') #CHNAGE
    
    class Meta:
        unique_together = ('user', 'post') 

    def __str__(self):
        return f'{self.user.username}: {self.post.title}'


class Choice(models.Model):
    post =  models.ForeignKey(Post, on_delete=models.CASCADE)
    title =  models.CharField(max_length=255)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title  


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('choice', 'user')

    def __str__(self):
        return f'USER: ({self.user.username}): CHOICE({self.choice.title}) - POST({self.choice.post.title} Has {self.choice.post.choice_set.all().count()} choices)'

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created_at =models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name="comment_replies")
    
    is_pinned = models.BooleanField(default=False) #add this feature later


    def __str__(self):
        return self.post.title   
        
    class Meta:
        ordering = ['-created_at']

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="replies")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    metadata = models.JSONField(null=True, blank=True)
    
    def __str__(self):
        return self.content
        
    class Meta:
        ordering = ['created_at']


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.post.title}: {self.user.username}'
 
    class Meta:
        ordering = ['-created_at']    


class Repost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    original_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.original_post.title}'

    class Meta:
        ordering = ['-created_at']    


from account.models import *

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action_initiator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='action_initiator')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True,null=True)

    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=True, blank=True)
    follow = models.ForeignKey(Follow, on_delete=models.CASCADE, null=True, blank=True)
    
    is_read = models.BooleanField(default=False)
    liked = models.BooleanField(default=False)
    reposted = models.BooleanField(default=False)
    commented = models.BooleanField(default=False)
    replied = models.BooleanField(default=False)
    followed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        if self.post:
            return self.post.title
        elif self.follow:
            return f"Followed by {self.action_initiator}"
        else:
            return "Notification without a post or follow action"


    class Meta:
        ordering = ['-timestamp']

   


from .signals import *
    

src/account/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import EmailValidator  # Import EmailValidator


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['banner', 'pic', 'website', 'bio', 'location']


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, validators=[EmailValidator()])  # Add EmailValidator to the email field

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email is already in use.')
        return email


class InboxForm(forms.ModelForm):
    class Meta:
        model = Inbox
        fields = ['content']


class CircleCreationForm(forms.ModelForm):
    class Meta:
        model = Circle
        fields = ['pfp', 'name', 'description', 'privacy']


class CirclePostForm(forms.ModelForm):
    class Meta:
        model = CirclePost
        fields = ['title', 'img']

src/account/templates/includes/user_posts.html
{% load static %}
{% load custom_tags %}


<div>
{% for post in unique_posts %}
 



  {% if post.choices_added %}  


  {% if post.is_repost %}

  
    <div class="flex items-center gap-2 font-semibold text-sm text-gray-400">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" class="w-5 h-5 ">
       <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 00-3.7-3.7 48.678 48.678 0 00-7.324 0 4.006 4.006 0 00-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3l-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 003.7 3.7 48.656 48.656 0 007.324 0 4.006 4.006 0 003.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3l-3 3" />
     </svg> Reposted
    </div>
    
    {% for repost in post.repost_set.all %}

    {% if repost.user == profile.user %}

   
 
    <div class="relative">
      <span class="repost-line"></span>

      <div class="ml-2">
       <p class="font-semibold text-woodsmoke-200">{{repost.content}}</p>
       <small class="text-gray-400"> {{ repost.created_at|elapsed_time  }} </small>
      </div>
    </div>   


      {% endif %}

    {% endfor %}

  {% endif %}

  <div class="flex items-center relative my-2">
    

      <div class="post-container" class="flex">
        

          <div class="text-gray-500 text-sm absolute right-0 top-0">
            <span>{{ post.created_at|elapsed_time }}</span>
          </div>
      
          <a class="text-base text-white hover:text-waikawa-gray-400 absolute left-12 top-0 font-semibold hover:underline" href="{% url 'account:profile' post.author.username %}">
            <span class="post-author">{{ post.author }}</span>
          </a>
      </div>

      

      {% if post.author.profile.pic %}
          <img  src="{{ MEDIA_URL }}{{ post.author.profile.pic.url }}" alt="Profile Image" class="profile-image rounded-md w-[40px] h-[40px]"
          >
        {% else %}
          <img src="{% static 'account/images/default_pic.jpg' %}" alt="Default Profile Picture" class="rounded-md w-[40px] h-[40px] "
          >
      {% endif %}

  </div>

  
    
  <a class="font-semibold my-2 text-white hover:text-waikawa-gray-400" href="{% url 'post_detail' post.slug %}">
    {{ post.title }}
  </a>

  {% if post.content %}
    <h2 class="text-waikawa-gray-300 text-base my-1 ">{{ post.content|remove_hashtags|truncatechars:250 }}</h2>
  {% endif %}

  {% if post.file %}
    {% if post.file.name|lower|endswith:'.mp4' %}
        <video class=" my-3 rounded-sm object-cover" controls  style="width:510px; height:300px;">
            <source src="{{ post.file.url }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    {% elif post.file.name|lower|endswith:'.jpg' or post.file.name|lower|endswith:'.jpeg' or post.file.name|lower|endswith:'.png' or post.file.name|lower|endswith:'.gif' %}


    <img src="{{ post.file.url }}" alt="Image" class="my-3 rounded-sm object-cover thumbnail-image" style="width: 510px; height: 250px;">

    {% else %}
        <p>This file type is not supported.</p>
    {% endif %}
  {% endif %}
    
          <!-- TAG -->
  <div class="flex items-center gap-2 text-white text-opacity-75 font-semibold my-2">
    <div>
    {% for tag in post.tag_set.all %}
      <a class="hover:text-pink-300 hover:underline text-base" href="{% url 'tag' tag.text %}?=72{{ tag.id }}45{{ tag.id }}82">#{{ tag.text }}</a>
    {% endfor %}
    </div>
  </div> 

    
  {% for get_view in posts_with_view_counts %}
        {% if post.id == get_view.post.id %}
            {% if get_view.view_count %}
                <p class="text-sm font-semibold text-gray-500 my-1">{{ get_view.view_count }} Reads</p>
            {% else %}
                <p class="text-sm font-semibold text-gray-500 my-1">No reads yet :(</p>
            {% endif %}
        {% endif %}
  {% endfor %}
    

  <div class="flex items-center gap-2 text-gray-600 ">
              
    <form class="upvote-form" method="POST" action="{% url 'upvote' post.slug %}">
            {% csrf_token %} 
          <button type="submit" class="text-gray-600 hover:text-gray-400">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941" />
            </svg><span class="upvote-count">{{ post.upvote_set.count }}</span>
          </button>
    </form>

                <!--DOWNVOTE ICON -->
    <form class="downvote-form" method="POST" action="{% url 'downvote' post.slug %}">
            {% csrf_token %}  
          <button type="submit"class="text-gray-600 hover:text-gray-400">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 13.5L12 21m0 0l-7.5-7.5M12 21V3" />
              </svg><span class="downvote-count">{{ post.downvote_set.count }}</span>  
          </button>
    </form>

                <!--COMMENT ICON -->
    <div class="flex flex-col items-center mr-auto">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
      </svg>{{ post.comments.all.count }} 
    </div>

                <!--BOOKMARK ICON -->
    <form class="bookmark-form-mainpage" method="post" action="{% url 'add_to_bookmark' post.slug %}">
                    {% csrf_token %}
        <button type="submit" class="text-gray-600 hover:text-gray-400">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" />
          </svg><span class="bookmark-count-home">{{ post.bookmark_set.all.count }}</span>
        </button> 
    </form>

  </div>          
  <!--END-->


              <!--VOTING-->
  {% if user|has_voted_for_post:post %}
              <!-- RESULTS SECTION -->
    <div id="results-card-container"  class="results-section mb-4 mt-2 p-2 rounded-md shadow-inner" style="border:1px solid #1E1B4B;">
      <h3 class="my-2 text-gray-500">Results:</h3>

      {% for choice in post.choice_set.all %}

        <div class="flex items-center gap-2">

          <div class="flex justify-between shadow-inner text-gray-300 text-semibold bg-gradient-to-r from-[#2911b3] to-transparent hover:bg-pink-700 rounded-md px-2 py-1 my-1 w-[300px] text-sm">
            <span class="truncate flex items-center">{{ choice.title }} 

                {% for user in choice.vote_set.all %}
                  {% if request.user == user.user %}
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-6 h-6 text-green-500 -mt-1">
                    <path fill-rule="evenodd" d="M6.293 9.293a1 1 0 0 1 1.414 0L10 11.586l2.293-2.293a1 1 0 0 1 1.414 1.414l-3 3a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 0-1.414z"/>
                  </svg>
                  {% endif %}
                {% endfor %}
                
              </span>
              {% if choice.vote_count > 0 %}
                <div class="relative w-full h-4 rounded-md bg-gradient-to-r from-blue-500 to-purple-500">
                  <div class="absolute top-0 left-0 h-full rounded-md bg-[#8f4972]" style=""></div>
                </div>
              {% endif %}

              <span class="text-gray-500 font-semibold ml-auto">{{ choice.vote_set.count }} Votes
                  {% for poll_total in count|post_total_votes %}
                  {% if poll_total.id == post.id %}
                  {{ choice.vote_set.count|calculate_percentage:poll_total.total_votes|floatformat:1 }}%
                  {% endif %}
                  {% endfor %}
              </span>

           
        </div> <!--remove p-->

        <div class="flex items-center text-gray-500">
          {% for user_vote in choice.vote_set.all|slice:":2"  %}
            {% if user_vote %}
            {% if user_vote.user.profile.pic %}
                <a href="{% url 'account:profile' user_vote.user %}">
                <img src="{{ MEDIA_URL }}{{ user_vote.user.profile.pic.url }}" alt="Profile Image" class=" border-3 rounded-full mx-2"  style="width:25px; height:25px; border: 3px solid transparent;" />
                </a>
                {% else %}
                <a href="{% url 'account:profile' user_vote.user %}">
                  <img src="{% static 'account/images/default_pic.jpg' %}" alt="Default Profile Picture" class="border-3 rounded-full mx-2"  style="width:25px; height:25px; border: 3px solid transparent;"/>
                </a>
            {% endif %} 
            <!--small>{{ user_vote.user }}</!--small--> 
            {% endif %}
          {% endfor %}
          
          {% with remaining_votes=choice.vote_set.count|subtract:2|add:"0" %}
            {% if remaining_votes > 0 %}
              <a class="flex text-xs font-semibold hover:underline hover:text-gray-500" href=""> +{{ remaining_votes }} </a> 
            {% endif %}
          {% endwith %}     
      </div>
    </div>  
    

      {% endfor %}

      <p class="mt-2 text-sm text-gray-400">
        {% for poll_total in count|post_total_votes %}
        {% if poll_total.id == post.id %}
        {{ poll_total.total_votes }} Votes
        {% endif %}
        {% endfor %}
      </p>  

      <p id="message-vote" class="mt-2 text-sm text-gray-400">You have already voted for this post.</p>
    </div>
    {% else %}
              <!--VOTING FORM -->
    <div id="voting-form-container"> 

      <form class="vote-form" method="POST" action="{% url 'home' %}">
        {% csrf_token %}
        <input type="hidden" name="post_slug" value="{{ post.slug }}">

        {% for choice in post.choice_set.all %}

            <div class="bar flex justify-between shadow-inner text-gray-300 text-semibold hover:bg-opacity-25 rounded-md px-2 py-1 my-1 w-[300px] text-sm">
              
              {% if user.is_authenticated %}
              {% if post.choice_set.all %}

              {% if choice.title|length > 15 %}
                <button type="submit" class="choice-button text-base font:semibold text-left" hover:font-semibold name="choice" value="{{ choice.id }}" data-choice-title="{{ choice.title }}">
                      <p class="text-white hover:underline">{{ choice.title|truncatechars:25  }}</p>
                </button>
                {% else %}
                <button type="submit" class="choice-button text-base" hover:font-semibold name="choice" value="{{ choice.id }}" data-choice-title="{{ choice.title }}">
                  <p class="text-white hover:underline">{{ choice.title }}</p>
                </button>
              {% endif %}

              {% endif %}
              {% else %}
              {% if post.choice_set.all %}
                <a href="{% url 'account:login' %}" class="hover:text-white hover:underline"> {{ choice.title }}</a>
              {% endif %}
              {% endif %}

        
              <span class="vote-count text-base text-gray-400 font-semibold" data-choice="{{ choice.id }}">{{ choice.vote_set.count }} Votes
                {% for poll_total in count|post_total_votes %}
                {% if poll_total.id == post.id %}
                {{ choice.vote_set.count|calculate_percentage:poll_total.total_votes|floatformat:1 }}%
                {% endif %}
                {% endfor %}
              </span>
          
            </div>

            
          
        {% endfor %}

        {% if post.choice_set.count > 1 %}
          <p class="mt-2 text-sm text-gray-400">
            {% for poll_total in count|post_total_votes %}
            {% if poll_total.id == post.id %}
            {{ poll_total.total_votes }} Votes
            {% endif %}
            {% endfor %}
          </p> 
        {% endif %}
        
      </form>
      <hr class="text-gray-700 my-3 shadow-sm rounded-xl">

    </div>
  {% endif %}



 
  
  {% endif %}

  {% empty %}
  No posts available yet
  
{% endfor %}
  </div>