src/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CircleCreateView, CircleDeleteView

app_name = 'account'
urlpatterns = [
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/profile/<str:username>/',
         views.profile_view, name='profile'),
    path('accounts/profile/<str:username>/edit/',
         views.edit_profile_view, name='edit_profile'),
    path('accounts/profile/<str:username>/remove_pic/',
         views.remove_profile_pic, name='remove_profile_pic'),
    path('accounts/profile/<str:username>/remove_banner/',
         views.remove_banner_pic, name='remove_banner'),
    path('accounts/profile/inbox/<str:username>/', views.inbox, name='inbox'),
    path('inbox/conversation/<str:username>/<int:message_id>/',
         views.conversation, name='conversation'),

    path('accounts/profile/circle/<str:circle_name>/',
         views.circle_detail_view, name='circle-detail'),
    path('accounts/profile/circle/<int:pk>/delete/',
         CircleDeleteView.as_view(), name='circle-delete'),
    path('accounts/profile/cir/create/',
         CircleCreateView.as_view(), name='circle-create'),

    path('accounts/profile/<str:username>/notifications/',
         views.notification, name='notifications'),

    path('accounts/profile/circle/<str:circle_name>/like',
         views.like_view, name='like'),



]

src/app/urls.py
from django.urls import path
from . import views

from .views import BookmarkListView,  CategoryListView, SearchView, PostDeleteView, HashtagsView

urlpatterns = [
    path('', views.home, name='home'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    
    path('post/<int:post_id>/repost/', views.repost_view, name='repost'),


    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete_view, name='comment-delete'),

    path('post/<int:post_pk>/comment/<int:comment_pk>/<int:reply_pk>/delete/', views.reply_delete_view, name='reply-delete'),


    path('search/', views.SearchView.as_view(), name='search'),
    path('hashtags/', HashtagsView.as_view(), name='hashtags'),
    
    path('people_search', views.people_search, name='people_search'),

    

    path('post/<slug:slug>/upvote/', views.upvote, name='upvote'),
    path('post/<slug:slug>/downvote/', views.downvote, name='downvote'),  

    path('accounts/profile/bookmark_list/', BookmarkListView.as_view(),  name='bookmark_list'), 

    path('post/<slug:slug>/add_to_bookmark', views.add_or_remove_bookmark, name='add_to_bookmark'),
    path('post/<slug:slug>/remove_from_bookmark', views.add_or_remove_bookmark, name='remove_from_bookmark'),




    path('create_post/', views.create_post_view, name='create_post'), 

    path('add-choice/<slug:slug>/', views.add_choices, name='add_choices'), 
    path('delete-choice/<int:pk>/', views.delete_choice, name='delete_choice'),

    path('category/<str:category>/', CategoryListView.as_view(), name='tag'), 

    path('group_search/', views.group_search, name='group_search'), 

    


    
]

src/web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),

    path('', include('account.urls')),

    path('', include('django.contrib.auth.urls')),



    path("__reload__/", include("django_browser_reload.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/account/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to='images/pfp', blank=True)
    banner = models.ImageField(upload_to='images/banners/', blank=True)
    bio = models.TextField(blank=True)
    website = models.URLField(max_length=150, blank=True)
    following = models.ManyToManyField(
        'self', symmetrical=False, related_name='followers', blank=True)
    created_at = models.DateTimeField(default=datetime.now)
    is_active = models.BooleanField(default=False)
    is_verify = models.BooleanField(default=False)

    CONTINENT_CHOICES = (
        ('Africa', 'Africa'),
        ('Antarctica', 'Antarctica'),
        ('Asia', 'Asia'),
        ('Europe', 'Europe'),
        ('North America', 'North America'),
        ('Oceania', 'Oceania'),
        ('South America', 'South America'), )

    location = models.CharField(
        max_length=20, choices=CONTINENT_CHOICES, blank=True)

    def __str__(self):
        return self.user.username

    def __str__(self):
        return f'{self.user.username} -followers: {self.followers.count()}'

from .signals import *

class Inbox(models.Model):
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='sent_messages')
    receiver = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='received_messages')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.content

    class Meta:
        ordering = ['-created_at']


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.profile.user.username


class Circle(models.Model):
    PRIVACY_CHOICES = [
        ('private', 'Private'),
        ('public', 'Public'),]

    host = models.OneToOneField(User, on_delete=models.CASCADE)
    pfp = models.ImageField(upload_to='Circle_pfps/', blank=True, null=True)
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField(blank=True)
    members = models.ManyToManyField(User, related_name='people', blank=True)
    privacy = models.CharField(
        max_length=10, choices=PRIVACY_CHOICES, default='public')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class CirclePost(models.Model):
    circle = models.ForeignKey(Circle, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=280, blank=True)
    img = models.ImageField(upload_to='circle_post_images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Post in {self.circle}"


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    circlepost = models.ForeignKey(CirclePost, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username}: {self.circlepost.title[:20]}'

src/app/models.py
from django.db import models
from django.contrib.auth.models import User

#automatically add a slug 
from django.utils.text import slugify

from account.models import Profile




# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    file = models.FileField(upload_to='files/', null=True, blank=True) 
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    choices_added = models.BooleanField(default=False)

    #automatically add a unique slug 
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            unique_slug = base_slug
            suffix = 1
            
            while Post.objects.filter(slug=unique_slug).exists():
                suffix += 1
                unique_slug = f"{base_slug}-{suffix}"

            self.slug = unique_slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

#TAG
class Tag(models.Model):
    text = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE) 

    def __str__(self):
        return f'{self.text}: {self.post.title}'

class Upvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    upvotes = models.ManyToManyField(User, related_name='post_upvotes') #CHANGE 
    
    class Meta:
        unique_together = ('user', 'post') 

    def __str__(self):
        return f'{self.user.username}: {self.post.id}'

   
        
            


class Downvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    downvotes = models.ManyToManyField(User, related_name='post_downvotes') #CHNAGE
    
    class Meta:
        unique_together = ('user', 'post') 

    def __str__(self):
        return f'{self.user.username}: {self.post.title}'


class Choice(models.Model):
    post =  models.ForeignKey(Post, on_delete=models.CASCADE)
    title =  models.CharField(max_length=255)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title  


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('choice', 'user')

    def __str__(self):
        return f'USER: ({self.user.username}): CHOICE({self.choice.title}) - POST({self.choice.post.title} Has {self.choice.post.choice_set.all().count()} choices)'

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created_at =models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name="comment_replies")
    
    is_pinned = models.BooleanField(default=False) #add this feature later


    def __str__(self):
        return self.post.title   
        
    class Meta:
        ordering = ['-created_at']

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="replies")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    metadata = models.JSONField(null=True, blank=True)
    
    def __str__(self):
        return self.content
        
    class Meta:
        ordering = ['created_at']


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.post.title}: {self.user.username}'
 
    class Meta:
        ordering = ['-created_at']    


class Repost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    original_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.original_post.title}'

    class Meta:
        ordering = ['-created_at']    


from account.models import *

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action_initiator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='action_initiator')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True,null=True)

    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=True, blank=True)
    follow = models.ForeignKey(Follow, on_delete=models.CASCADE, null=True, blank=True)
    
    is_read = models.BooleanField(default=False)
    liked = models.BooleanField(default=False)
    reposted = models.BooleanField(default=False)
    commented = models.BooleanField(default=False)
    replied = models.BooleanField(default=False)
    followed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        if self.post:
            return self.post.title
        elif self.follow:
            return f"Followed by {self.action_initiator}"
        else:
            return "Notification without a post or follow action"


    class Meta:
        ordering = ['-timestamp']

   


from .signals import *
    

src/account/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import EmailValidator  # Import EmailValidator


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['banner', 'pic', 'website', 'bio', 'location']


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, validators=[EmailValidator()])  # Add EmailValidator to the email field

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('This email is already in use.')
        return email


class InboxForm(forms.ModelForm):
    class Meta:
        model = Inbox
        fields = ['content']


class CircleCreationForm(forms.ModelForm):
    class Meta:
        model = Circle
        fields = ['pfp', 'name', 'description', 'privacy']


class CirclePostForm(forms.ModelForm):
    class Meta:
        model = CirclePost
        fields = ['title', 'img']

src/account/templates/all_messages.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
  <div class="sticky top-12 py-3 backdrop-blur-md w-full z-20">
    <div class="flex justify-between items-center font-semibold mt-2">
      <a class="font-semibold text-gray-400 hover:text-gray-300 hover:underline w-auto" href="#" onclick="goBack()">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />
        </svg>
      </a>
      <div class="mr-4">
        <h1 class="text-xl semibold ml-auto">{{ username }}</h1>
        Total messages {{ messages_count }}
      </div>
    </div>
  </div>
  <h1 class="my-4">All Messages</h1>
  <div class="flex flex-col h-screen">
    <div class="p-2 rounded-lg mt-3 overflow-y-auto flex-grow" id="message-container">
    {% for message in messages %}
      <div class="my-4">
        <div class="flex gap-1 items-center relative">
          <div class="">
            {% if message.sender.profile.pic %}
              <a href="{% url 'account:profile' message.sender.username %}"><img src="{{ MEDIA_URL }}{{ message.sender.profile.pic.url }}" alt="Profile Image" class="border-3 rounded-full mx-1" style="width: 35px; height: 35px; border: 3px solid transparent" /></a>
            {% else %}
              <a href="{% url 'account:profile' message.sender.username %}"><img src="{% static 'account/images/default_pic.jpg' %}" alt="Default Profile Picture" class="border-3 rounded-full mx-1" style="width: 35px; height: 35px; border: 3px solid transparent" /></a>
            {% endif %}
          </div>
        </div>
        <small class="text-xs text-gray-500 ml-1 mb-2">{{ message.created_at|timesince }} Ago</small>
        <h2 class="text-gray-300 font-semibold p-1 rounded-lg ml-auto">{{ message.content }}</h2>
      </div>
    {% endfor %}
  </div>
  <div class="w-full sticky bottom-0 p-2 rounded">
    <form method="post" class="message-form rounded-md" action="{% url 'account:conversation' username message_id %}">
      {% csrf_token %}
      <div class="flex items-center">
        <input type="text" name="{{ form.content.name }}" placeholder="Message" class="bg-[#2C2C2C] w-full text-gray-200 py-2 px-4 rounded-full focus:outline-none focus:ring-2" required />
        <button type="submit" class="ml-2 px-4 py-1 text-white rounded-full bg-[#8C5E58] hover:opacity-75">Send</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

src/account/templates/circle.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}
{% block content %}
  <div id="circle-template" class="flex flex-col mt-4 relative">
    <div class="flex justify-center items-center">
      <div class="bg-[#1b1a2c] w-full rounded-sm p-1">
        {% if circle_obj.pfp %}
          <img src="{{ MEDIA_URL }}{{ circle_obj.pfp.url }}" alt="Profile Picture" class="rounded-md object-cover w-[115px] h-[105px]" />
        {% else %}
          <div class="bg-[#515372] w-[115px] h-[105px] shadow-inner rounded-sm p-2 flex justify-center items-center text-2xl">?</div>
        {% endif %}
      </div>
    </div>
    <div class="mt-6 mb-2 mr-auto text-gray-300">
      <div class="">
        <h1 class="text-2xl font-semibold">{{ circle_obj.name }}</h1>
        <p class="my-2 text-gray-300">{{ circle_obj.members.count }} Members</p>
        <div class="flex items-center gap-1 my-2 text-sm">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75m-3-7.036A11.959 11.959 0 013.598 6 11.99 11.99 0 003 9.749c0 5.592 3.824 10.29 9 11.623 5.176-1.332 9-6.03 9-11.622 0-1.31-.21-2.571-.598-3.751h-.152c-3.196 0-6.1-1.248-8.25-3.285z" />
          </svg>
          {{ circle_obj.host }}
        </div>
        {% if circle_obj.host == request.user %}

        {% else %}
          <form method="post" class="join-leave-form mt-2 absolute right-0 top-24" action="{% url 'account:circle-detail' circle_obj.name %}">
            <input type="hidden" name="join_leave" value="true" />
            {% csrf_token %}
            {% if request.user in circle_obj.members.all %}
              <button type="submit" id="join-leave-button" class="bg-gray-600 bg-opacity-25 hover:bg-opacity-40 text-white font-semibold py-1 px-2 rounded" name="action" value="leave">Leave</button>
            {% else %}
              <button type="submit" id="join-leave-button" class="bg-gray-600 bg-opacity-25 hover:bg-opacity-40 text-white font-semibold py-1 px-2 rounded" name="action" value="join">Join</button>
            {% endif %}
          </form>
        {% endif %}
      </div>
      <p class="my-2">{{ circle_obj.description }}</p>
      <small>Since: {{ circle_obj.created_at|date:'F j, Y' }}</small>
    </div>
    {% if request.user == circle_obj.host %}
      <a href="{% url 'account:circle-delete' circle_obj.id %}" class="text-base text-red-500 hover:text-red-600 underline my-2">Delete</a>
    {% endif %}
    <hr class="text-gray-600 mt-1" />
    {% if user in circle_obj.members.all %}

      <form method="POST" enctype="multipart/form-data" class="circle-post-form" action="{% url 'account:circle-detail' circle_obj.name %}">
        <input type="hidden" name="create_circle_post" value="true" />
        {% csrf_token %}
        <div class="mb-1 flex gap-4 items-center">
          <div class="flex">
            <input type="text" id="{{ circle_post_form.title.id_for_label }}" name="{{ circle_post_form.title.name }}" placeholder="What do you want to share?" class="px-4 py-3 bg-[#1b1a2c] w-[230px] text-white border-0 rounded-sm text-sm focus:outline-none focus:border-gray-600 focus:ring-2" required />
          </div>
          <div>
            <label for="{{ circle_post_form.img.id_for_label }}" class="text-gray-400 cursor-pointer b">
              <i class="fas fa-image fa-lg"></i>
              <input type="file" id="{{ circle_post_form.img.id_for_label }}" name="{{ circle_post_form.img.name }}" class="inset-0 opacity-0 w-20  cursor-pointer focus:outline-none" />
            </label>
          </div>
        </div>
      </form>
    {% endif %}
    {% if circle_obj.privacy == 'public' or user in circle_obj.members.all %}
      <div class="">
        {% if circle_posts %}
          {% for post in circle_posts %}
            <div class="my-6 ml-4">
              <div class="flex gap-2 items-center">
                {% if post.user.profile.pic %}
                  <a href="{% url 'account:profile' post.user.username %}"><img src="{{ MEDIA_URL }}{{ post.user.profile.pic.url }}" alt="Profile Image" class="border-2 rounded-md" style="width:37px;
                                height:37px;
                                border: 3px solid transparent" /></a>
                {% else %}
                  <a href="{% url 'account:profile' post.user.username %}"><img src="{% static 'account/images/default_pic.jpg' %}" alt="Default Profile Picture" class="border-2 rounded-md" style="width:37px;
                                height:37px;
                                border: 3px solid transparent" /></a>
                {% endif %}
                <div>
                  <p class="text-sm mr-2 font-semibold text-woodsmoke-100">{{ post.user }}</p>
                  <small class="text-xs text-gray-500">{{ post.created_at|elapsed_time }}</small>
                </div>
              </div>
              <h1 class="font-semibold my-2 text-gray-100 break-words">{{ post.title }}</h1>
              <div class="break-words">
                <p class="my-3">{{ post.content }}</p>
                <div class="relative my-3">
                  {% if post.img %}
                    <img src="{{ MEDIA_URL }}{{ post.img.url }}" alt="Profile Picture" class="rounded-md object-cover w-[580px] h-[308px]" />
                  {% endif %}
                </div>
                <div class="flex items-center gap-2 text-gray-400">
                  <form class="like-form" method="POST" action="{% url 'account:like' post.circle.name %}">
                    <input type="hidden" name="circle_post" value="{{ post.id }}" />
                    {% csrf_token %}
                    <button type="submit">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
                      </svg>
                    </button>
                  </form>
                  <span class="mb-1 text-sm">{{ post.like_set.count }}</span>
                  {% for like in post.like_set.all|limit_users:10 %}
                    {% if like.user.profile.pic %}
                      <a href="{% url 'account:profile' like.user.username %}"><img src="{{ MEDIA_URL }}{{ like.user.profile.pic.url }}" alt="Profile Image" class="border-2 rounded-full" style="width:28px;
                                    height:28px;
                                    border: 3px solid transparent" /></a>
                    {% else %}
                      <a href="{% url 'account:profile' like.user.username %}"><img src="{% static 'account/images/default_pic.jpg' %}" alt="Default Profile Picture" class="border-2 rounded-full" style="width:28px;
                                    height:28px;
                                    border: 3px solid transparent" /></a>
                    {% endif %}
                  {% endfor %}
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <p class="flex justify-center items-center mt-12">No posts yet.</p>
        {% endif %}
      </div>
    {% else %}
      <div class="flex justify-center items-center my-12">this content is private only joined Members can see it</div>
    {% endif %}
  </div>
{% endblock %}

src/account/templates/circle_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <div class="mt-12">
    <h2 class="text-xl font-semibold mb-2">Delete Forever</h2>
    {% if request.user == circle.host %}
      <p class="text-red-600">Are you sure you want to delete your circle "{{ circle.name }}"?</p>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-600 hover:bg-red-700 py-1 px-2 rounded my-3">Confirm</button>
      </form>
      <a href="{% url 'account:circle-detail' circle.name %}" class="text-lg hover:underline text-gray-400 hover:text-gray-600 mt-6 ml-1">Cancel</a>
    {% else %}
      <p class="mb-4 text-gray-600">You do not have permission to delete this post.</p>
      <a href="{% url 'account:circle-detail' circle.name %}" class="text-lg hover:underline text-gray-400 hover:text-gray-600 mt-6 ml-1">Go back</a>
    {% endif %}
  </div>
{% endblock %}