src/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import CircleCreateView, CircleDeleteView

app_name = 'account'
urlpatterns = [
    path('accounts/register/', views.register_view, name='register'),
    path('accounts/login/', views.login_view, name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/profile/<str:username>/',
         views.profile_view, name='profile'),
    path('accounts/profile/<str:username>/edit/',
         views.edit_profile_view, name='edit_profile'),
    path('accounts/profile/<str:username>/remove_pic/',
         views.remove_profile_pic, name='remove_profile_pic'),
    path('accounts/profile/<str:username>/remove_banner/',
         views.remove_banner_pic, name='remove_banner'),
    path('accounts/profile/inbox/<str:username>/', views.inbox, name='inbox'),
    path('inbox/conversation/<str:username>/<int:message_id>/',
         views.conversation, name='conversation'),

    path('accounts/profile/circle/<str:circle_name>/',
         views.circle_detail_view, name='circle-detail'),
    path('accounts/profile/circle/<int:pk>/delete/',
         CircleDeleteView.as_view(), name='circle-delete'),
    path('accounts/profile/cir/create/',
         CircleCreateView.as_view(), name='circle-create'),

    path('accounts/profile/<str:username>/notifications/',
         views.notification, name='notifications'),

    path('accounts/profile/circle/<str:circle_name>/like',
         views.like_view, name='like'),



]

src/app/urls.py
from django.urls import path
from . import views

from .views import BookmarkListView,  CategoryListView, SearchView, PostDeleteView, HashtagsView

urlpatterns = [
    path('', views.home, name='home'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    
    path('post/<int:post_id>/repost/', views.repost_view, name='repost'),


    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

    path('post/<int:post_pk>/comment/<int:comment_pk>/delete/', views.comment_delete_view, name='comment-delete'),

    path('post/<int:post_pk>/comment/<int:comment_pk>/<int:reply_pk>/delete/', views.reply_delete_view, name='reply-delete'),


    path('search/', views.SearchView.as_view(), name='search'),
    path('hashtags/', HashtagsView.as_view(), name='hashtags'),
    
    path('people_search', views.people_search, name='people_search'),

    

    path('post/<slug:slug>/upvote/', views.upvote, name='upvote'),
    path('post/<slug:slug>/downvote/', views.downvote, name='downvote'),  

    path('accounts/profile/bookmark_list/', BookmarkListView.as_view(),  name='bookmark_list'), 

    path('post/<slug:slug>/add_to_bookmark', views.add_or_remove_bookmark, name='add_to_bookmark'),
    path('post/<slug:slug>/remove_from_bookmark', views.add_or_remove_bookmark, name='remove_from_bookmark'),




    path('create_post/', views.create_post_view, name='create_post'), 

    path('add-choice/<slug:slug>/', views.add_choices, name='add_choices'), 
    path('delete-choice/<int:pk>/', views.delete_choice, name='delete_choice'),

    path('category/<str:category>/', CategoryListView.as_view(), name='tag'), 

    path('group_search/', views.group_search, name='group_search'), 

    


    
]

src/web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),

    path('', include('account.urls')),

    path('', include('django.contrib.auth.urls')),



    path("__reload__/", include("django_browser_reload.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/app/models.py
from django.db import models
from django.contrib.auth.models import User

#automatically add a slug 
from django.utils.text import slugify

from account.models import Profile




# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True)
    file = models.FileField(upload_to='files/', null=True, blank=True) 
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    choices_added = models.BooleanField(default=False)

    #automatically add a unique slug 
    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(self.title)
            unique_slug = base_slug
            suffix = 1
            
            while Post.objects.filter(slug=unique_slug).exists():
                suffix += 1
                unique_slug = f"{base_slug}-{suffix}"

            self.slug = unique_slug
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']

#TAG
class Tag(models.Model):
    text = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE) 

    def __str__(self):
        return f'{self.text}: {self.post.title}'

class Upvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    upvotes = models.ManyToManyField(User, related_name='post_upvotes') #CHANGE 
    
    class Meta:
        unique_together = ('user', 'post') 

    def __str__(self):
        return f'{self.user.username}: {self.post.id}'

   
        
            


class Downvote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    downvotes = models.ManyToManyField(User, related_name='post_downvotes') #CHNAGE
    
    class Meta:
        unique_together = ('user', 'post') 

    def __str__(self):
        return f'{self.user.username}: {self.post.title}'


class Choice(models.Model):
    post =  models.ForeignKey(Post, on_delete=models.CASCADE)
    title =  models.CharField(max_length=255)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title  


class Vote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('choice', 'user')

    def __str__(self):
        return f'USER: ({self.user.username}): CHOICE({self.choice.title}) - POST({self.choice.post.title} Has {self.choice.post.choice_set.all().count()} choices)'

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    created_at =models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name="comment_replies")
    
    is_pinned = models.BooleanField(default=False) #add this feature later


    def __str__(self):
        return self.post.title   
        
    class Meta:
        ordering = ['-created_at']

class Reply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name="replies")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    metadata = models.JSONField(null=True, blank=True)
    
    def __str__(self):
        return self.content
        
    class Meta:
        ordering = ['created_at']


class Bookmark(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.post.title}: {self.user.username}'
 
    class Meta:
        ordering = ['-created_at']    


class Repost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    original_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.original_post.title}'

    class Meta:
        ordering = ['-created_at']    


from account.models import *

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    action_initiator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='action_initiator')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True,null=True)

    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE, null=True, blank=True)
    follow = models.ForeignKey(Follow, on_delete=models.CASCADE, null=True, blank=True)
    
    is_read = models.BooleanField(default=False)
    liked = models.BooleanField(default=False)
    reposted = models.BooleanField(default=False)
    commented = models.BooleanField(default=False)
    replied = models.BooleanField(default=False)
    followed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        if self.post:
            return self.post.title
        elif self.follow:
            return f"Followed by {self.action_initiator}"
        else:
            return "Notification without a post or follow action"


    class Meta:
        ordering = ['-timestamp']

   


from .signals import *
    

src/app/templates/includes/additional_content_left.html
{% load static %}

<div class="fixed top-20 hidden xl:block lg:block lg:left-6 xl:left-[120px] lg:w-[220px] 2xl:ml-7 p-1 xl:w-[220px] flex justify-center items-center mr-auto mt-1 flex-col">

 <form class="relative" id="search-form" method="GET">
    <input id="search-input" type="text" name="query" placeholder="Search" class="top-0 sticky mb-4 px-4 lg:w-[210px] xl:w-full text-gray-200 bg-[#2C2C2C] outline-none rounded-sm py-2 focus:border-transparent" />
 </form>
  
  
 <div class="text-white">
    <div class="absolute my-1 mb-2 z-50 rounded backdrop-blur-md text-gray-900 mx-auto transition-opacity duration-300 ease-in-out w-full"
        id="search-results">
    </div>
 </div>
  
 <img class="rounded-sm xl:w-[220px] opacity-75 lg:w-[220px] h-[179px]" src="{% static 'logo/cat.png' %}" alt="Mountain Image">

 <p class="text-white font-semibold mt-4 lg:text-sm xl:text-base">"Join our diverse community and discover the happiness of sharing thoughts with others."</p>
  


 
 <div class="lg:left-6 xl:left-14 xl:block lg:block  mt-12 flex items-center gap-2 hidden">
   {% if user.is_authenticated %}

<div class="flex items-center gap-2 rounded py-1 px-3">
 <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-gray-300" style="transform: rotate(-179deg)">
   <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 9V5.25A2.25 2.25 0 0013.5 3h-6a2.25 2.25 0 00-2.25 2.25v13.5A2.25 2.25 0 007.5 21h6a2.25 2.25 0 002.25-2.25V15m3 0l3-3m0 0l-3-3m3 3H9"/>
 </svg>
 <a href="{% url 'account:logout' %}" class="text-gray-100 hover:text-gray-300 hover:underline" >
   Sing Out
 </a>
</div>

 {% else %}
 <div class="flex flex-col gap-3 my-4 rounded-sm relative w-[212px] ">
   <div>
     <a href="{% url 'account:login' %}">
       <button class="bg-[#2911b3] text-white font-semibold py-1 px-3 rounded w-full" style="border: 1px solid #1a202c">
         Login
       </button>
     </a>
   </div>

   <div>
     <a href="{% url 'account:register' %}">
       <button class="hover:bg-[#2911b3] text-white font-semibold py-1 px-3 rounded w-full" style="border: 1px solid #1a202c">
        Create account</button>
     </a>
 </div>

 {% endif %}
</div>
</div>

 
</div>  

src/app/templates/includes/additional_content_right.html
{% load static %}
{% load custom_tags %}

<div class="overflow-y-auto scrollbar h-[600px] fixed top-20 mt-1 xl:right-[126px] text-white w-[300px] lg:block lg:right-6 lg:w-[210px] hidden xl:block rounded-sm border-l-2 border-[#2C2C2C] p-1">
  <p class="text-white font-semibold my-2 ml-1">Trending</p>
  <p class="text-gray-400 ml-1">
    {% date_format %}
  </p>

  <div class="absolute mt-3">
    <ul>
      {% get_tags as tags_queryset %}
      {% for tag in tags_queryset %}
        <li class="flex flex-col mt-2 mb-3 ml-1">
          <div class="flex gap-2 items-center">
            <a class="hover:text-white hover:underline" href="{% url 'tag' tag.text %}?={{ tag.id }}">#{{ tag.text }}</a>
          </div>
      
          <div class="">
            <div class="flex gap-2 justify-between items-center">
              <small class="text-gray-400">{{ tag.post_count }} posts</small>
              <small class="text-gray-400">{{ tag.people_using_tag }} user{{ tag.people_using_tag|pluralize:'s' }}</small>
            </div>
      
            <div class="flex items-center gap-2">
              <small class="text-emerald-400 text-xs">{{ tag.last_post_date|elapsed_time }}</small>
              {% if tag.max_post_title %}
                <p class="text-gray-400 text-sm">{{ tag.max_post_title|truncatechars:25 }}</p>
              {% endif %}
            </div>
          </div>
        </li>
      {% endfor %}
      
    </ul>
  </div>
</div>

src/app/templates/includes/posts.html
{% load static %}
{% load custom_tags %}
<div class="flex items-center relative">
  <div class="flex gap-2 ">
    {% if post.author.profile.pic %}
      <img src="{{ MEDIA_URL }}{{ post.author.profile.pic.url }}"
           alt="Profile Image"
           class="rounded-md w-[40px] h-[40px]">
    {% else %}
      <img src="{% static 'account/images/default_pic.jpg' %}"
           alt="Default Profile Picture"
           class="rounded-md w-[40px] h-[40px]">
    {% endif %}
    <div class="ml-1">
      <a href="{% url 'account:profile' post.author.username %}">
        <p class="text-sm  font-bold hover:text-gray-100 hover:underline">{{ post.author }}</p>
      </a>
      <a class="font-semibold "
         href="{% url 'post_detail' post.slug %}">
        <small class="text-xs text-gray-500">{{ post.created_at|elapsed_time }}</small>
      </a>
    </div>
  </div>
</div>
<div class="my-2">
  <a class="font-semibold break-words hover:text-gray-200"
     href="{% url 'post_detail' post.slug %}">{{ post.title }}</a>
</div>
{% if post.content %}
  <h2 class="text-waikawa-gray-300 text-base my-2">{{ post.content|remove_hashtags|truncatechars:340 }}</h2>
{% endif %}
{% if post.file %}
  {% if post.file.name|lower|endswith:'.mp4' %}
    <video class=" my-3 rounded-sm object-cover mx-auto"
           controls
           style="width:548px;
                  height:300px">
      <source src="{{ post.file.url }}" type="video/mp4">
      Your browser does not support the video tag.
    </video>
  {% elif post.file.name|lower|endswith:'.jpg' or post.file.name|lower|endswith:'.jpeg' or post.file.name|lower|endswith:'.png' or post.file.name|lower|endswith:'.gif' or post.file.name|lower|endswith:'.webp' %}
    <img src="{{ post.file.url }}"
         alt="Image"
         class="my-3 rounded-sm mx-auto object-cover thumbnail-image"
         style="width: 548px;
                height: 250px">
  {% else %}
    <p>This file type is not supported.</p>
  {% endif %}
{% endif %}
<!-- TAG -->
<div class="flex items-center gap-2 text-white text-opacity-75 font-semibold ">
  <div>
    {% for tag in post.tag_set.all %}
      <a class="hover:text-transparent hover:bg-clip-text hover:bg-gradient-to-r hover:from-fuchsia-400 hover:to-purple-600 hover:underline text-base relative"
         href="{% url 'tag' tag.text %}?=72{{ tag.id }}45{{ tag.id }}82">#{{ tag.text }}</a>
    {% endfor %}
  </div>
</div>
{% for get_view in posts_with_view_counts %}
  {% if post.id == get_view.post.id %}
    {% if get_view.view_count %}
      <p class="text-sm font-semibold text-gray-500 my-1">{{ get_view.view_count }} Views</p>
    {% else %}
      <p class="text-sm font-semibold text-gray-500 my-1">No views yet :(</p>
    {% endif %}
  {% endif %}
{% endfor %}
<!--USERS LINK UPVOTE & DOWNVOTE-->
<div class="flex items-center gap-2 text-gray-600 mt-2">
  {% if user.is_authenticated %}
    <form class="upvote-form"
          method="POST"
          action="{% url 'upvote' post.slug %}">
      {% csrf_token %}
      <div class="flex flex-col items-center">
        <button type="submit">
          <svg xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 24 24"
               stroke-width="1.5"
               stroke="currentColor"
               class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941" />
          </svg>
        </button>
        <span class="upvote-count">{{ post.upvote_set.count }}</span>
      </div>
    </form>
    <form class="downvote-form"
          method="POST"
          action="{% url 'downvote' post.slug %}">
      {% csrf_token %}
      <div class="flex flex-col items-center">
        <button type="submit">
          <svg xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 24 24"
               stroke-width="1.5"
               stroke="currentColor"
               class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 13.5L12 21m0 0l-7.5-7.5M12 21V3" />
          </svg>
        </button>
        <span class="downvote-count">{{ post.downvote_set.count }}</span>
      </div>
    </form>
  {% else %}
    <!--NON USERS LINK UPVOTE & DOWNVOTE-->
    <div class="flex flex-col items-center">
      <svg xmlns="http://www.w3.org/2000/svg"
           fill="none"
           viewBox="0 0 24 24"
           stroke-width="1.5"
           stroke="currentColor"
           class="w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 18L9 11.25l4.306 4.307a11.95 11.95 0 015.814-5.519l2.74-1.22m0 0l-5.94-2.28m5.94 2.28l-2.28 5.941" />
      </svg>
      <span id="upvote-count-{{ post.id }}">{{ post.upvote_set.count }}</span>
    </div>
    <div class="flex flex-col items-center">
      <svg xmlns="http://www.w3.org/2000/svg"
           fill="none"
           viewBox="0 0 24 24"
           stroke-width="1.5"
           stroke="currentColor"
           class="w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 13.5L12 21m0 0l-7.5-7.5M12 21V3" />
      </svg>
      <span id="downvote-count-{{ post.id }}">{{ post.downvote_set.count }}</span>
    </div>
  {% endif %}
  <!--COMMENT ICON -->
  <div class="flex flex-col items-center mr-auto">
    <svg xmlns="http://www.w3.org/2000/svg"
         fill="none"
         viewBox="0 0 24 24"
         stroke-width="1.5"
         stroke="currentColor"
         class="w-5 h-5">
      <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 8.511c.884.284 1.5 1.128 1.5 2.097v4.286c0 1.136-.847 2.1-1.98 2.193-.34.027-.68.052-1.02.072v3.091l-3-3c-1.354 0-2.694-.055-4.02-.163a2.115 2.115 0 01-.825-.242m9.345-8.334a2.126 2.126 0 00-.476-.095 48.64 48.64 0 00-8.048 0c-1.131.094-1.976 1.057-1.976 2.192v4.286c0 .837.46 1.58 1.155 1.951m9.345-8.334V6.637c0-1.621-1.152-3.026-2.76-3.235A48.455 48.455 0 0011.25 3c-2.115 0-4.198.137-6.24.402-1.608.209-2.76 1.614-2.76 3.235v6.226c0 1.621 1.152 3.026 2.76 3.235.577.075 1.157.14 1.74.194V21l4.155-4.155" />
    </svg>
    {{ post.total_comment_count }}
  </div>
  <!--BOOKMARK ICON -->
  {% if user.is_authenticated %}
    <!--REPOST ICON -->
    <form class="repost-form"
          method="post"
          action="{% url 'repost' post.id %}"
          data-post-id="{{ post.id }}">
      {% csrf_token %}
      <div class="flex flex-col items-center mr-2">
        <div onclick="toggleDropdown('{{ post.id }}')"
             class="flex flex-col items-center mr-2"
             data-post-id="{{ post.id }}">
          <svg xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 24 24"
               stroke-width="1.5"
               stroke="currentColor"
               class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 00-3.7-3.7 48.678 48.678 0 00-7.324 0 4.006 4.006 0 00-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3l-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 003.7 3.7 48.656 48.656 0 007.324 0 4.006 4.006 0 003.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3l-3 3" />
          </svg>
          <span>{{ post.repost_set.all.count }}</span>
        </div>
      </div>
      <div id="buttons-{{ post.id }}"
           class="z-20 hidden absolute flex flex-col right-0 text-black rounded-sm opacity-80 bg-[#cfcfec] mr-0 p-4 transition-opacity duration-500">
        {% if not post.has_reposted %}
          <button class="hover:text-[#1A0FB3]" type="submit">Repost</button>
          <button type="button"
                  onclick="showContentField('{{ post.id }}')"
                  id="quote-button-{{ post.id }}">Quote</button>
        {% else %}
          <button class="hover:text-[#1A0FB3]" type="submit">undone</button>
        {% endif %}
      </div>
      <div id="contentField-{{ post.id }}"
           class="hidden absolute right-0 left-0 flex flex-col z-50 ">
        <div class="bg-white rounded-md p-4 border border-gray-300 m-2">
          <div class="flex items-start space-x-4">
            <!-- User Avatar -->
            <div class="w-12 h-12 bg-gray-300 rounded-full">
              {% if request.user.profile.pic %}
              <a href="{% url 'account:profile' user.profile %}">
                <img src="{{ MEDIA_URL }}{{ request.user.profile.pic.url }}"
                     alt="Profile Image"
                     class=" border-3 rounded-full w-12 h-12"/>
              </a>
            {% else %}
              <a href="{% url 'account:profile' user.profile %}">
                <img src="{% static 'account/images/default_pic.jpg' %}"
                     alt="Default Profile Picture"
                     class="border-3 rounded-full w-12 h-12"/>
          
              </a>
            {% endif %}
            </div>
            <!-- Post Content -->
            <div class="flex-grow">
              <textarea name="content"
                        rows="3"
                        placeholder="Add a public comment..."
                        class="w-full p-2 border rounded-md resize-none focus:ring-2  focus:outline-none focus:border-[#291094]"></textarea>
              <div class="flex justify-end mt-2">
                <button type="submit"
                        class="px-2 py-1 bg-[#291094] text-white text-base rounded-md hover:bg-[#1e0b6e]">
                  Repost
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
    <form class="bookmark-form-mainpage"
          method="post"
          action="{% url 'add_to_bookmark' post.slug %}">
      {% csrf_token %}
      <div class="flex flex-col items-center">
        <button type="submit" class="text-gray-600 hover:text-gray-400">
          <svg xmlns="http://www.w3.org/2000/svg"
               fill="none"
               viewBox="0 0 24 24"
               stroke-width="1.5"
               stroke="currentColor"
               class="w-5 h-5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" />
          </svg>
        </button>
        <span class="bookmark-count-home">{{ post.bookmark_set.all.count }}</span>
      </div>
    </form>
  {% else %}
    <!--REPOST ICON -->
    <div class="flex flex-col items-center mr-2">
      <svg xmlns="http://www.w3.org/2000/svg"
           fill="none"
           viewBox="0 0 24 24"
           stroke-width="1.5"
           stroke="currentColor"
           class="w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 12c0-1.232-.046-2.453-.138-3.662a4.006 4.006 0 00-3.7-3.7 48.678 48.678 0 00-7.324 0 4.006 4.006 0 00-3.7 3.7c-.017.22-.032.441-.046.662M19.5 12l3-3m-3 3l-3-3m-12 3c0 1.232.046 2.453.138 3.662a4.006 4.006 0 003.7 3.7 48.656 48.656 0 007.324 0 4.006 4.006 0 003.7-3.7c.017-.22.032-.441.046-.662M4.5 12l3 3m-3-3l-3 3" />
      </svg>
      <span>{{ post.repost_set.all.count }}</span>
    </div>
    <div class="flex flex-col items-center">
      <svg xmlns="http://www.w3.org/2000/svg"
           fill="none"
           viewBox="0 0 24 24"
           stroke-width="1.5"
           stroke="currentColor"
           class="w-5 h-5">
        <path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.25 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" />
      </svg>
      <span class="bookmark-count-home">{{ post.bookmark_set.all.count }}</span>
    </div>
  {% endif %}
</div>